### ISSUE TITLE
handle authentication failure

### ISSUE THREAD

**Issue by hichtakk** [hichtakk/nsxctl#29]
If credential information is wrong, nsxctl cause panic.

```
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/hichtakk/nsxctl/client.(*NsxtClient).GetVersion(...)
        /Users/hichikawa/go/src/github.com/hichtakk/nsxctl/client/infra.go:82
github.com/hichtakk/nsxctl/cmd.NewCmdShowVersion.func2(0xc000157b80?, {0x143d236?, 0x0?, 0x0?})
        /Users/hichikawa/go/src/github.com/hichtakk/nsxctl/cmd/version.go:52 +0x145
github.com/spf13/cobra.(*Command).execute(0xc000157b80, {0x180d438, 0x0, 0x0})
        /Users/hichikawa/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc000157680)
        /Users/hichikawa/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/hichikawa/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
        /Users/hichikawa/go/src/github.com/hichtakk/nsxctl/main.go:9 +0x25
```

**Comment by hichtakk** [comment]
need to suppress help message.

```
$ nsxctl show version             
Error: authentication failed
Usage:
  nsxctl show version [flags]

Aliases:
  version, v

Flags:
      --alb    show NSX ALB version
  -h, --help   help for version

Global Flags:
  -c, --config string   path to nsxctl config file (default "/Users/hichikawa/.config/nsxctl.json")
      --debug           enable debug mode
      --site string     specify site name
```
